- name: mysql configuartion
  hosts: mysql
  become: yes
  vars:
   mysql_root_password: ExpenseApp@1
   login_host: mysql.devops20lpa.online
   
  tasks:
  - name: install mysql serve
    ansible.builtin.package:
     name: mysql-server
     state: present
    #since mysql will connect to aws through ansible which is python code , python my sql must downloaded to connect

  - name: ansible to install pymysql
    ansible.builtin.pip:
     name:
      - PyMySQL
     executable: pip3.9


  - name: start the server
    ansible.builtin.service:
     name: mysqld
     state: present
     enabled: yes

  - name: connect mysql server
    community.mysql.mysql_info:
     login_user: root
     login_password: "{{mysql_root_password}}"   
     login_host: "{{login_host}}" 
    ignore_errors: true
    register: mysql_info

  - name: print the mysql info
    ansible.builtin.debug: 
     msg: "{{mysql_info}}"

  - name: setup MySQL root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true  #this command will be executed if root password is not



  